freefood/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # JS API commands
    path("get-map-markers/", views.get_map_markers),
    path("get-map-history/", views.get_map_history),
    path("update-date/", views.update_date, name="update-date"),
    path("update-sort/<str:sortMethod>/", views.update_sort),
    path("update-toggle-show/", views.update_toggle_show), 
    path("update-dietary-restrictions/", views.update_dietary_restrictions, name="update-dietary"),
    path("image-by-event/<int:id>", views.get_image_by_event, name="image-by-event"), 
    path("image-by-id/<int:id>", views.get_image_by_id, name="image-by-id"),
    path("refresh-ajax/", views.updateAllFilters),
    path("submit-rating/<int:event_id>/<int:new_rating>", views.add_rating),
    path("markFinished/<int:event_id>", views.availability_finished),
    path("markAvailable/<int:event_id>", views.availability_available),
    path('add-comment/<int:event_id>', views.add_comment),
    path('get-global/<int:event_id>', views.get_comment),
    path("delete-event/<int:id>", views.delete_event, name="delete-event"),
    
    # Pages: 
    path('', views.index, name="index"),
    path('map', views.map, name="map"),
    path('heatmap', views.heatmap, name="heatmap"),
    path('event/<int:id>/', views.event_view, name="event_page"),
    path('new-event/', views.new_event, name="new_event"),
    path('edit-event/<int:id>/', views.edit_event, name="edit_event"),
    path('profile/', views.profile, name="profile"),
]

webapps/urls.py
from django.contrib import admin
from django.urls import path, include
from freefood import views, urls
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('freefood/', include(urls)),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('logout', auth_views.logout_then_login, name='logout'),
]

freefood/models.py
# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist

class Event(models.Model):
    # each event has one user who made it, copied from Post model (hw5)

    # Metadata:
    create_date     = models.DateTimeField(auto_now_add=True)
    rating          = models.FloatField(default=0)
    rating_num      = models.IntegerField(default=0)

    num_views       = models.IntegerField(default=0)
    available       = models.BooleanField(default=True)

    
    user            = models.ForeignKey(User, default=None, on_delete=models.PROTECT)

    # comments
    num_comments    = models.IntegerField(default=0) # would like to keep track 
                                                     # of this for sorting. 

    name_of_event   = models.CharField(max_length=100)
    food            = models.CharField(max_length=100)

    veg             = models.BooleanField(default=False)
    vn              = models.BooleanField(default=False)
    df              = models.BooleanField(default=False)
    gf              = models.BooleanField(default=False)

    date            = models.DateField() # datetime.date (year, month, day)
    start_time      = models.TimeField(null=True)
    end_time        = models.TimeField(null=True, blank=True)
    link            = models.CharField(max_length=500, null=True, blank=True)
    notes           = models.CharField(max_length=500, null=True, blank=True)
    
    location_lat    = models.FloatField()
    location_lng    = models.FloatField()

    building_name   = models.CharField(max_length=500)
    room_number     = models.CharField(max_length=500)


# These store the images. 
class EventImage(models.Model):
    image        = models.FileField()
    content_type = models.CharField(max_length=50)

    event        = models.ForeignKey(Event, on_delete=models.CASCADE, related_name="images")


class Rating(models.Model):
    # Event for the comment
    event       = models.ForeignKey(Event, on_delete=models.CASCADE, related_name="ratings")

    # Who made comment, when was comment made, etc. 
    user        = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_ratings")

    # 1 <= value <= 5
    value       = models.IntegerField()


class Comment(models.Model):
    # Event for the comment
    event       = models.ForeignKey(Event, default=None, on_delete=models.CASCADE, related_name="comments")

    # Who made comment, when was comment made, etc. 
    user        = models.ForeignKey(User, on_delete=models.PROTECT)
    create_date = models.DateTimeField(auto_now_add=True)

    # what does the comment actually contain?
    content     = models.CharField(max_length=500)

    # replies to comment (optional? just putting it here for now)
    replies     = models.ForeignKey('self', on_delete=models.CASCADE, null=True)


# This entire model is optional, but would potentially be an interesting addition.
class Like(models.Model):
    # who liked the comment?
    user        = models.ForeignKey(User, on_delete=models.CASCADE)

    # likes are for comments
    comment     = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name="likes")

    # value
    like        = models.IntegerField(default=0)


# Profile model 
class Profile(models.Model):
    user            = models.OneToOneField(User, on_delete=models.PROTECT, related_name="profile")
    events          = models.ManyToManyField(Event, related_name="events")
    picture          = models.FileField()
    content_type    = models.CharField(max_length=50)

freefood/forms.py
from django import forms
from django.forms import Textarea, DateInput, TimeInput, SelectMultiple
 
from freefood.models import Event

MAX_UPLOAD_SIZE = 2500000
 
class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['name_of_event', 'food', 'veg', 'vn', 'df', 'gf', 'date', 'start_time', 'end_time', 
                  'link', 'notes', 'location_lat', 'location_lng', 
                  'building_name', 'room_number']
       
        widgets = {
            "notes" : Textarea(attrs={'cols': 60, 'rows': 3}),
            # 'image': forms.FileInput(attrs={'id':'id_food_image'}),
            "location_lat": forms.HiddenInput(),
            "location_lng": forms.HiddenInput(),
        }
    address = forms.CharField(required=True)
    image = forms.FileField(required=False)

    def clean_image(self):
        picture = self.cleaned_data['image']
        if not picture or not hasattr(picture, 'content_type'):
            return None         # it should probably be ok to *not* submit a picture. 
        if not picture.content_type or not picture.content_type.startswith('image'):
            raise forms.ValidationError('File type is not image')
        if picture.size > MAX_UPLOAD_SIZE:
            raise forms.ValidationError('File too big (max size is {0} bytes)'.format(MAX_UPLOAD_SIZE))
        return picture


class DateRangeForm(forms.Form):
    startDate = forms.DateField(required=False)
    endDate = forms.DateField(required=False)

class RestrictionsForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['veg', 'vn', 'df', 'gf']
    
class AllFiltersForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['veg', 'vn', 'df', 'gf']

    sort = forms.CharField()
    startDate = forms.DateField(required=False)
    endDate = forms.DateField(required=False)
    happeningNow = forms.CharField()


class UploadImageForm(forms.Form):
    image = forms.FileField(required=True)

    def clean_image(self):
        picture = self.cleaned_data['image']
        if not picture or not hasattr(picture, 'content_type'):
            raise forms.ValidationError('Please actually include an image. ')
        if not picture.content_type or not picture.content_type.startswith('image'):
            raise forms.ValidationError('File type is not image')
        if picture.size > MAX_UPLOAD_SIZE:
            raise forms.ValidationError('File too big (max size is {0} bytes)'.format(MAX_UPLOAD_SIZE))
        return picture

freefood/templates/freefood/subtemplates/event_form.html
{% load widget_tweaks %}

{% csrf_token %}

<!-- Place hidden fields into the form -->
{% for field in form.hidden_fields %}
    {{ field }}
{% endfor %}

<div class="container" style="width: 70%;">
    <!-- Place visible fields into the form.  -->
    <div class="col-12">
        <label for="{{ form.name_of_event.id_for_label }}" class="form-label">{{ form.name_of_event.label }}<strong class="required-indicator">*</strong></label>
        {% render_field form.name_of_event class="form-control" %}
        {% include "freefood/subtemplates/new_event_help_errors.html" with field=form.name_of_event %}
        <div class="invalid-feedback">Please choose a name for the event.</div>
    </div>
    <p></p>
    <div class="col-12">
        <label for="{{ form.food.id_for_label }}" class="form-label">{{ form.food.label }}<strong class="required-indicator">*</strong></label>
        {% render_field form.food class="form-control" %}
        {% include "freefood/subtemplates/new_event_help_errors.html" with field=form.food %}
        <div class="invalid-feedback">Please describe the food.</div>
    </div>
    <p></p>
    <!-- buttons go here  -->
    <div class="col-12" id="buttons">
        <label for="id_veg" class="form-label">Dietary Options Available</label><br>

        {% render_field form.veg class="btn-check" type="checkbox" autocomplete="off" %}
        <label class="btn btn-outline-secondary" for="id_veg">Vegetarian</label>

        {% render_field form.vn class="btn-check" type="checkbox" autocomplete="off" %}
        <label class="btn btn-outline-secondary" for="id_vn">Vegan</label>

        {% render_field form.df class="btn-check" type="checkbox" autocomplete="off" %}
        <label class="btn btn-outline-secondary" for="id_df">Dairy Free</label>
        
        {% render_field form.gf class="btn-check" type="checkbox" autocomplete="off" %}
        <label class="btn btn-outline-secondary" for="id_gf">Gluten Free</label>
        
    </div>
    <p></p>
    <div class="row">
        <div class="col-md-6">
            <label for="{{ form.date.id_for_label }}" class="form-label">{{ form.date.label }}<strong class="required-indicator">*</strong></label>
            {% render_field form.date class="form-control" type="date" %}
            {% include "freefood/subtemplates/new_event_help_errors.html" with field=form.date %}
            <div class="invalid-feedback">Please select a date.</div>
        </div>

        <div class="col-md-3">
            <label for="{{ form.start_time.id_for_label }}" class="form-label">{{ form.start_time.label }}<strong class="required-indicator">*</strong></label>
            {% render_field form.start_time class="form-control" type="time" %}
            {% include "freefood/subtemplates/new_event_help_errors.html" with field=form.start_time %}
            <div class="invalid-feedback">Please select a start time.</div>
        </div>

        <div class="col-md-3">
            <label for="{{ form.end_time.id_for_label }}" class="form-label">{{ form.end_time.label }}</label>
            {% render_field form.end_time class="form-control" type="time" %}
            {% include "freefood/subtemplates/new_event_help_errors.html" with field=form.end_time %}
        </div>
    </div>
    
    <p></p>
    <div class="col-12">
        <label for="{{ form.link.id_for_label }}" class="form-label">{{ form.link.label }}</label>
        {% render_field form.link class="form-control" type="url" %}
        {% include "freefood/subtemplates/new_event_help_errors.html" with field=form.link %}
        <div class="invalid-feedback">Please use a valid url.</div>
    </div>
    <p></p>
    <div class="col-12">
        <label for="{{ form.notes.id_for_label }}" class="form-label">{{ form.notes.label }}</label>
        {% render_field form.notes class="form-control" %}
        {% include "freefood/subtemplates/new_event_help_errors.html" with field=form.notes %}
    </div>
    <p></p>
    <div class="col-12">
        <label for="{{ form.image.id_for_label }}" class="form-label">{{ form.image.label }}</label>
        {% render_field form.image class="form-control" %}
        {% include "freefood/subtemplates/new_event_help_errors.html" with field=form.image %}
    </div>
    <p></p>
    <!-- variable names need some work. -->
    <div class="col-12">
        <label for="map-set-location" class="form-label">Location<strong class="required-indicator">*</strong></label>
        <div class="input-group has-validation" id="map-set-location">
            <button class="btn btn-outline-secondary" type="button" id="set-current-loc-btn" onclick="set_current_location()">Current Location</button>
            {% render_field form.address class="form-control disabled-input" tabindex="-1" aria-describedby="set-current-loc-btn set-current-loc-error" %}
            <!-- <input id="id_address" type="text" class="form-control disabled-input" tabindex="-1" aria-describedby="set-current-loc-btn set-current-loc-error" required> -->
            <div class="invalid-feedback" id="set-current-loc-error">Please select a location on the map. </div>
        </div>
        <div id="coordinate-error">
            {% include "freefood/subtemplates/new_event_help_errors.html" with field=form.location_lat %}
            {% include "freefood/subtemplates/new_event_help_errors.html" with field=form.location_lng %}
        </div>
        <!-- 
            <small class="form-text text-danger">Enter a number.</small>
            console.log((document.getElementById("coordinate-error").innerHTML) == ok);
        -->
    </div>

    <div class="form-field">
        <!-- <label for="new-event-map" class="form-label">Select a Location</label> -->
        <div id="new-event-map"></div>

        <script
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB4--DpVDid7yY_Uqt6Pm1NL_NSN2eSty4&callback=initMap&v=weekly"
            defer
        ></script>
    </div>
    <p></p>
    <div class="row">
        <div class="col-md-6">
            <label for="{{ form.building_name.id_for_label }}" class="form-label">{{ form.building_name.label }}<strong class="required-indicator">*</strong></label>
            {% render_field form.building_name class="form-control" %}
            {% include "freefood/subtemplates/new_event_help_errors.html" with field=form.building_name %}
            <div class="invalid-feedback">Please provide a building/area.</div>
        </div>

        <div class="col-md-6">
            <label for="{{ form.room_number.id_for_label }}" class="form-label">{{ form.room_number.label }}<strong class="required-indicator">*</strong></label>
            {% render_field form.room_number class="form-control" %}
            {% include "freefood/subtemplates/new_event_help_errors.html" with field=form.room_number %}
            <div class="invalid-feedback">Please choose a room number.</div>
        </div>
    </div>

    <p></p>
    <div class="col text-center"> 
        <button class="btn btn-primary btn-lg" style="width:300px">{{ form_function }}</button>
    </div>
</div>

freefood/templates/freefood/subtemplates/header.html
<nav class="navbar navbar-dark navbar-expand-lg">
    <div class="container-fluid">
        <div class="navbar-nav">
            {% if page == "map" %}
                <a class="nav-link active" style="text-decoration:underline;" aria-current="page" href="{% url 'map' %}">Map</a>
            {% else %}
                <a class="nav-link" href="{% url 'map' %}">Map</a>
            {% endif %}

            {% if page == "heatmap" %}
                <a class="nav-link active" style="text-decoration:underline;" aria-current="page" href="{% url 'heatmap' %}">History</a>
            {% else %}
                <a class="nav-link" href="{% url 'heatmap' %}">History</a>
            {% endif %}

            {% if page == 'new_event' %}
                <a class="nav-link active" style="text-decoration:underline;" aria-current="page" href="{% url 'new_event' %}">New Event</a>
            {% else %}
                <a class="nav-link" href="{% url 'new_event' %}">New Event</a>
            {% endif %}
            
            {% if page == 'profile' %}
                <a class="nav-link active" style="text-decoration:underline;" aria-current="page" href="{% url 'profile' %}">Profile</a>
            {% else %}
                <a class="nav-link" href="{% url 'profile' %}">Profile</a>
            {% endif %}

        </div>
    </div>
</nav>

freefood/templates/freefood/subtemplates/new_event_help_errors.html
{% if field.help_text %}
<small class="form-text text-muted">{{ field.help_text }}</small>
{% endif %}
{% for error in field.errors %}
<small class="form-text text-danger">{{ error }}</small>

{% if error == "Enter a number." %}
<div class="modal" id="stop-hacking-modal" tabindex="-1">
    <div class="modal-dialog modal-fullscreen modal-warning">
      <div class="modal-content modal-warning">
        <div class="modal-header">
          <h1 class="modal-title">💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀</h1>
          <!-- <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button> -->
        </div>
        <div class="modal-body text-center my-auto">


          <br><br><br>


          <h1>S̵̡̧̛̻͍̝͓̯̠͎̙͈̥͖̗̦̰̩̬̦̥̱͔̞̲̥̬̦̜̝̮̙̤̱̤̙̝̪̦͖̿̏́̀̑̆͐͛̎͒̀̍̌́̒͋̒͂́̑̓̽͐̑̐̈̽̚͠͝Ṭ̴̛̭̖̖̝̪̠̠̫̩̜͉̹̥͔̬̯̣͛̆̀̏͂̀͛̉͑͑̌̋̉̌͛̍̾̌̍͊̍̿̈͛͑̈́̂̈̔̾͂̚̚͝͠͝͝ͅƠ̶̥̼̙̹̙͑̓̓̀̽͌͂͐̒̈́̓͂̈́͑͐̀̓̎̑͊̀̏͆̀̆̂̾̄̅̕̕̚͠P̵̣̖͉̫͆̆̈́̓͌̓̂ͅ ̶̢̧̫̺͈͖̗̙̖̼͈̘͙̭̞̼̱̪͖͎̝̟̱͓̟̩̖̟̗̪̘̬̘̳̼̺̹͚̘̮̦͍̣̲̇̽̿̄̀̉̍̏̀̽́̃͗͛̋̈́̓̈́́̐̏͂͂̍̈̓̃̀̈̑́̽͌̓̈́̓͊̄̇̆̀̃͘̚̕̚͜͝͝͠ͅŢ̶̜̤̤̳̩̲̲͍̺̻̼̭̞̙̬̜̩͚̩̫̰̹̥͇̪̱̣̰͚̹̀̍͑̊́́̀̆̂͌̇̑̓̈̿̆̎̇͑̅͌͛̊̄͘̕͜͜͝͠ͅR̷̡̡̛̛̛̦͔̣̹̉̾̂̋̀͂̍̉̇̏̔̀̈́͊̏̓͒͌̈́̀̏̇̎̎̀͘̕͠͝͝͝Y̴̛͎͈̲͍̪͒̊̈́͜Į̵̛̰͎̗͇̗̙͖̣̗̪̯̰͙̣̟̭͖̗̬̞̖̟͎̫̰̥̖̝͕̯̲̩̦̜̈́͆̽̈́̎́̅͒͋̔̉̀̈́͊̂͗̅́͊̽́̈́̌͊͘̚͜͜͜͠Ņ̵̧̡̡̠̟̣͙̬̟̱̼͇̝͔̮͚̪͕̲̝͚͔̟̦̟̩̜͎̲͉̥͇̒̂̆̊͆̎̾̍̔͛̄̊͋̀͊͒̇̋̈́̇͆̕̚͜͝G̵̛̻͎͇͚̞̐̈́̀͐̐̿̎̿͂́̔̇̄̒͂͋̓̌̆͋̐͌̀́̆̑͛̍̀͂̏̚̕͘̕͝͝ ̵̡̡̙͚̙̟̗͔̱̯̭̙̙̼̪͚͈͕̟͉̦̻̮̦̺͇̻̈́͌́̉̓̏̉̾̓̊͗̽́̈̃̄̆͂̚͘͘Ţ̸͛͐̈́̓̐̆̔̋̌̀̈́̈́̍͊̿̈́̌̋̕̚̚̕̕̚͝͠Ǫ̴̡̧̡̛͖͉͇̪̞̠̳̘̫̦̗̘̙͈̦̫͓̱̠̻̼̯̩̠̝͙̙̥̖̬̦͎̠͇͍̽̉̇̌̽̓̃̾̋̌͌͛͗͆̀̈́̈́͗̈͐̓̂͂̎͂̍̈̉̾̎̌̂̀̃͊͊͑̌̇̚̚̕͘̕͜͜͜͜͝͝͝ ̸̢̡̛͈̬̫̺͍͇̝͈̝̈́̉̓̒̊͑́̅͛́̑̂̎̓́̉̓́̂̄́̑̎͐͑̎̌̑̊̄̆̉͘͝͝͝ͅH̵̨̩͕͈̖̠̓̿Á̸̧̨̨̧̡̙̹̪͉̲͖̬͎͙͕͖̯͔̤͖͓͉͖͔̮̤͓͇̟͍̱͖̗̠̣̙̥̈́̈́̈́̌̇͌͊̈́̏͋̅̌͛͆́̋̾͠ͅC̴̢̧̨̹̯̪͇̹͇̜̺̯̖̥͕̗͚̭͔̖͙͖̪͇̪̬͍̳̥͖͎̖̣̔͋̓̋̄̄̅̒́́̇͊͛͊̀́̃̎̃̔̑͋͆̈̐̇̉̋͘͘͘͜ͅK̷̡̡̝̠̖̖̣̠̝͚̠̱͎͎̥̟͇̥̭̠̖̜̗̠̗͗̽̈́̈́͑̈́̇̓̄̎͆͋͌́͛͛̊̀͊͝͝ ̷̡̟̗͎̩̳͓̖̥̫̦̘̦̲͚̖̱͖̯̅̇̈̌͋̀̿͊̽̉́̏͆͌̐̀̀̅̓̑̂̍͑̆͋̎̏̈͊́́̅͑̓̕͘̚̚͠͝T̶̨̨̨̧̪̭̞͖̝͖͔̲̺̰͔̙̜͓̖͖̭͖͔͕͍̥͎̟̬̱̬̝͉͕̗̼̻̠̀̌̃̊̔̀͊̒͛͜͝ͅḨ̶̢̼͚̣̠͚͔̘͕̹̟̲̻̖̠͈̝̿̒́̋͛͐̓͌͂̕̚͠ͅȨ̴͈̺͇͖̰̩̈́͒̇̈́͛́̍͋̎̾͆͗̇̎͐̃͘ ̶̪̺͙͙̲̹̬̩̺̾͋̍̀̈́̉͐̔͆̋̇̍̄̐̏̾̎͝Ẅ̶̡̧̛̛̭͒͆̉̑̈́̋̀́̀̽̐̂̈́̐͑͑͑͜͝͝͝͠͠E̸̢̡̢̢̧̙͍͉̲̬̟̫͎͙͓͕̬̫̟͚̻͍̖̩̤͚̞̰̭͔͉̤̖̗̬̜̖͙͍̪̲͐̇͌̑̋̀̕͜ͅB̴̨̢̨̛̺̭͈̺̫̩̳͓̲̳͓͈͚͇̪͍̻̮͍͔̘̪̜͓̝͎̥̮̟͇̳̫̟̪̱̳͚͖̜͓̤̣̮͊͛͗̽̋̈́́̇̀̅͌̂̊̂͆͒͐͛̄̃̓̒̌̈͒̀̀̓̔͌̊͛̀͂̂̈́͑̚͜͜͝͝͝͝͠ͅͅȘ̴̛̛͈̞͖̹͇̳̰̞̝͙̯̥̦̹̹̲͎̰͓̺̦̤̰͙͍̌̉̓̄͐͑̎̈́̌̋̿̉̑͋̈́̊͌̈́̒̍̌̿̈́͝͝͝ͅḮ̵̡̢̡̧̨̨̡̡̖͎̳͇̳͎̙̮̳͍̠͕̦̖̠͕̩͖̮̭̺̰̫̙̩͉̥̥̫͔̠͔̪͍͓͇̦̋͌̑͊̽̀̊̈́̃̃̈͆͗͝ͅͅT̶̨̢̨̧̧̛͖̹̩̲̦̮̯͈̪̘̣̩͎̠̼̞̥̝̩̹͎̼̯͎̰̮̩͚̜̱̥͚̲͔̥̼̽̌̏͑͗̅͆̑̀͆̑̀̀̈́̾͐̿̐̌̌̓͒̏́̌͌̂̊̊̎͊͐͛͐̎͂̍̚͜͠͝͝ͅE̷̡̨̧̛̞̠̜̖̟̠̟͍͇͉͈̞̩̱͙̭͕̙̘̤̝̥͉̣̖͕͖̪̪̓̾̿̿̎́͌̔̈́̆̈̄́͗̃͒́͆̿͛͊̐̈́̿̈́̚̚̕̕̕͜͜͝ͅ</h1>
        </div>
        <div class="modal-footer">
          <!-- <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">I would like to sincerely apologize.</button> -->
          <button onclick="remove_modal();return false;" class="btn btn-secondary">I would like to sincerely apologize.</button>
        </div>
      </div>
    </div>
  </div>

  <script  src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous">
  </script>

  <script>
    $( document ).ready(function() {
        $("#stop-hacking-modal").modal('toggle');
    });
     
    function myTimer() {
        $("#stop-hacking-modal").modal('toggle');
    }
    // var myVar = setInterval(myTimer, 3000);
    var trolling = null;

    function remove_modal() {
      let text = `I would like to apologize for attempting to change the hidden fields on your website, and, more importantly, I must apologize for my total failure to trust in your ability to properly validate fields in the backend. I will be taking this incident very seriously and will make plans to ensure that I will never attempt to hack your website again.`
      let person = prompt(`Please type the following apology to continue:\n\n${text}`);

      if (person == text) {
        $("#stop-hacking-modal").modal('toggle');
      } else {
        alert("Please properly apologize. ")
        remove_modal();
      }
    }

  </script>
{% endif %}

{% endfor %}