freefood/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # JS API commands
    path("get-map-markers/", views.get_map_markers),
    path("get-map-history/", views.get_map_history),
    path("update-date/", views.update_date, name="update-date"),
    path("update-sort/<str:sortMethod>/", views.update_sort),
    path("update-toggle-show/", views.update_toggle_show), 
    path("update-dietary-restrictions/", views.update_dietary_restrictions, name="update-dietary"),
    path("image-by-event/<int:id>", views.get_image_by_event, name="image-by-event"), 
    path("image-by-id/<int:id>", views.get_image_by_id, name="image-by-id"),
    path("refresh-ajax/", views.updateAllFilters),
    path("submit-rating/<int:event_id>/<int:new_rating>", views.add_rating),
    path("markFinished/<int:event_id>", views.availability_finished),
    path("markAvailable/<int:event_id>", views.availability_available),
    path('add-comment/<int:event_id>', views.add_comment),
    path('get-global/<int:event_id>', views.get_comment),
    path("delete-event/<int:id>", views.delete_event, name="delete-event"),
    
    # Pages: 
    path('', views.index, name="index"),
    path('map', views.map, name="map"),
    path('heatmap', views.heatmap, name="heatmap"),
    path('event/<int:id>/', views.event_view, name="event_page"),
    path('new-event/', views.new_event, name="new_event"),
    path('edit-event/<int:id>/', views.edit_event, name="edit_event"),
    path('profile/', views.profile, name="profile"),
]

webapps/urls.py
from django.contrib import admin
from django.urls import path, include
from freefood import views, urls
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('freefood/', include(urls)),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('logout', auth_views.logout_then_login, name='logout'),
]

freefood/models.py
# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist

class Event(models.Model):
    # each event has one user who made it, copied from Post model (hw5)

    # Metadata:
    create_date     = models.DateTimeField(auto_now_add=True)
    rating          = models.FloatField(default=0)
    rating_num      = models.IntegerField(default=0)

    num_views       = models.IntegerField(default=0)
    available       = models.BooleanField(default=True)

    
    user            = models.ForeignKey(User, default=None, on_delete=models.PROTECT)

    # comments
    num_comments    = models.IntegerField(default=0) # would like to keep track 
                                                     # of this for sorting. 

    name_of_event   = models.CharField(max_length=100)
    food            = models.CharField(max_length=100)

    veg             = models.BooleanField(default=False)
    vn              = models.BooleanField(default=False)
    df              = models.BooleanField(default=False)
    gf              = models.BooleanField(default=False)

    date            = models.DateField() # datetime.date (year, month, day)
    start_time      = models.TimeField(null=True)
    end_time        = models.TimeField(null=True, blank=True)
    link            = models.CharField(max_length=500, null=True, blank=True)
    notes           = models.CharField(max_length=500, null=True, blank=True)
    
    location_lat    = models.FloatField()
    location_lng    = models.FloatField()

    building_name   = models.CharField(max_length=500)
    room_number     = models.CharField(max_length=500)


# These store the images. 
class EventImage(models.Model):
    image        = models.FileField()
    content_type = models.CharField(max_length=50)

    event        = models.ForeignKey(Event, on_delete=models.CASCADE, related_name="images")


class Rating(models.Model):
    # Event for the comment
    event       = models.ForeignKey(Event, on_delete=models.CASCADE, related_name="ratings")

    # Who made comment, when was comment made, etc. 
    user        = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_ratings")

    # 1 <= value <= 5
    value       = models.IntegerField()


class Comment(models.Model):
    # Event for the comment
    event       = models.ForeignKey(Event, default=None, on_delete=models.CASCADE, related_name="comments")

    # Who made comment, when was comment made, etc. 
    user        = models.ForeignKey(User, on_delete=models.PROTECT)
    create_date = models.DateTimeField(auto_now_add=True)

    # what does the comment actually contain?
    content     = models.CharField(max_length=500)

    # replies to comment (optional? just putting it here for now)
    replies     = models.ForeignKey('self', on_delete=models.CASCADE, null=True)


# This entire model is optional, but would potentially be an interesting addition.
class Like(models.Model):
    # who liked the comment?
    user        = models.ForeignKey(User, on_delete=models.CASCADE)

    # likes are for comments
    comment     = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name="likes")

    # value
    like        = models.IntegerField(default=0)


# Profile model 
class Profile(models.Model):
    user            = models.OneToOneField(User, on_delete=models.PROTECT, related_name="profile")
    events          = models.ManyToManyField(Event, related_name="events")
    picture          = models.FileField()
    content_type    = models.CharField(max_length=50)

freefood/forms.py
from django import forms
from django.forms import Textarea, DateInput, TimeInput, SelectMultiple
 
from freefood.models import Event

MAX_UPLOAD_SIZE = 2500000
 
class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['name_of_event', 'food', 'veg', 'vn', 'df', 'gf', 'date', 'start_time', 'end_time', 
                  'link', 'notes', 'location_lat', 'location_lng', 
                  'building_name', 'room_number']
       
        widgets = {
            "notes" : Textarea(attrs={'cols': 60, 'rows': 3}),
            # 'image': forms.FileInput(attrs={'id':'id_food_image'}),
            "location_lat": forms.HiddenInput(),
            "location_lng": forms.HiddenInput(),
        }
    address = forms.CharField(required=True)
    image = forms.FileField(required=False)

    def clean_image(self):
        picture = self.cleaned_data['image']
        if not picture or not hasattr(picture, 'content_type'):
            return None         # it should probably be ok to *not* submit a picture. 
        if not picture.content_type or not picture.content_type.startswith('image'):
            raise forms.ValidationError('File type is not image')
        if picture.size > MAX_UPLOAD_SIZE:
            raise forms.ValidationError('File too big (max size is {0} bytes)'.format(MAX_UPLOAD_SIZE))
        return picture


class DateRangeForm(forms.Form):
    startDate = forms.DateField(required=False)
    endDate = forms.DateField(required=False)

class RestrictionsForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['veg', 'vn', 'df', 'gf']
    
class AllFiltersForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['veg', 'vn', 'df', 'gf']

    sort = forms.CharField()
    startDate = forms.DateField(required=False)
    endDate = forms.DateField(required=False)
    happeningNow = forms.CharField()


class UploadImageForm(forms.Form):
    image = forms.FileField(required=True)

    def clean_image(self):
        picture = self.cleaned_data['image']
        if not picture or not hasattr(picture, 'content_type'):
            raise forms.ValidationError('Please actually include an image. ')
        if not picture.content_type or not picture.content_type.startswith('image'):
            raise forms.ValidationError('File type is not image')
        if picture.size > MAX_UPLOAD_SIZE:
            raise forms.ValidationError('File too big (max size is {0} bytes)'.format(MAX_UPLOAD_SIZE))
        return picture

freefood/templates/freefood/base.html
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Free Food{% endblock %}</title>

        <!-- Bootstrap5 -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

        <link rel="stylesheet" href="/static/freefood/default.css">

        <!-- Google -->
        <link href="https://fonts.googleapis.com/css2?family=Poppins" rel="stylesheet">

        <!-- favicon -->
        <link rel="icon" type="image/x-icon" href="/static/freefood/ui/favicon.ico" >

        <!-- JQuerry -->
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"
            integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
            crossorigin="anonymous">
        </script>
        {% block scripts %}{% endblock %}
    </head>

    <header>
        <div id="id_header_div" class="header">
            <a class="header-title" id="id_site_name" href="{% url 'index' %}">
                <img src="/static/freefood/ui/logo.png" style="width:40px;">
                Free Food @ CMU
            </a>
            {% block header %}
                {% include "freefood/subtemplates/header.html" with page="" %}
            {% endblock %}
        </div>
    </header>


    <body>        
        {% block body %}{% endblock %}

        <script>
        // Example starter JavaScript for disabling form submissions if there are invalid fields
        (() => {
          'use strict'
        
          // Fetch all the forms we want to apply custom Bootstrap validation styles to
          const forms = document.querySelectorAll('.needs-validation')
        
          // Loop over them and prevent submission
          Array.from(forms).forEach(form => {
            form.addEventListener('submit', event => {
              if (!form.checkValidity()) {
                event.preventDefault()
                event.stopPropagation()
              }
        
              form.classList.add('was-validated')
            }, false)
          })
        })()
        </script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    </body>

</html>

freefood/templates/freefood/edit_event.html
{% extends "freefood/base.html" %}

{% load widget_tweaks %}

{% block title %}Edit Event{% endblock %}

{% block scripts %}<script src="/static/freefood/new_event_map.js"></script>{% endblock %}

{% block header %}
    {% include "freefood/subtemplates/header.html" with page="edit_event" %}
{% endblock %}

{% block body %}     
    <form action="{% url 'edit_event' id %}" method="POST" enctype="multipart/form-data" class="row g-3 container-sm mx-auto needs-validation" novalidate>
        <page-title>Edit Event</page-title>
        {% include "freefood/subtemplates/event_form.html" with form_function="Save Changes" %}
    </form>

    <h1>&nbsp</h1>

    <script>
        // make a marker of the location lat/lng
        window.addEventListener("load", (event) => {
            let lat = parseFloat(document.getElementById("id_location_lat").value);
            let lng = parseFloat(document.getElementById("id_location_lng").value);

            set_selected_location(lat, lng);
        });
    </script>
{% endblock %}

freefood/templates/freefood/event_view.html
{% extends "freefood/base.html" %}

{% load widget_tweaks %}

{% block title %}Event{% endblock %}

{% block scripts %}
<script src="https://kit.fontawesome.com/980e4cc40c.js" crossorigin="anonymous"></script>
<script src="/static/freefood/event_view.js"></script>
{% endblock %}


{% block body %}
<div class="container" id="event-detail-view" data-value="{{id}}">
    <div class="row" style="margin-top:10px; margin-bottom:10px;">
		<div class="col">
			<button class="btn btn-primary btn-lg" style="width:100px; font-size:20px;  margin-right:10px;" onclick="history.back()">Back</button>   
		
			<!-- Buttons that open up confirmation button. -->
			{% if available %}
			<button type="button" class="btn btn-primary btn-lg" data-bs-toggle="modal" data-bs-target="#markFinishedModal" id="markFinishedButton">Mark Finished</button>
			<button type="button" class="btn btn-primary btn-lg hidden" data-bs-toggle="modal" data-bs-target="#markAvailableModal" id="markAvailableButton">Mark Available</button>
			{% else %}
			<button type="button" class="btn btn-primary btn-lg hidden" data-bs-toggle="modal" data-bs-target="#markFinishedModal" id="markFinishedButton">Mark Finished</button>
			<button type="button" class="btn btn-primary btn-lg" data-bs-toggle="modal" data-bs-target="#markAvailableModal" id="markAvailableButton">Mark Available</button>
			{% endif %}
		</div>
	</div>
	
    <!-- Finished Modal -->
    <div class="modal fade" id="markFinishedModal" tabindex="-1" aria-labelledby="markFinishedModalLabel" aria-hidden="true">
		<div class="modal-dialog modal-dialog-centered">
			<div class="modal-content">
			<div class="modal-header">
				<h1 class="modal-title fs-5" id="markFinishedModalLabel">Confirmation</h1>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				Are you sure you would like to mark this event as finished? This change will be reflected immediately. 
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
				<button type="button" class="btn btn-primary" onclick="changeAvailability('markFinished');return false;">Proceed</button>
			</div>
			</div>
		</div>
    </div>

    <!-- Available Modal -->
    <div class="modal fade" id="markAvailableModal" tabindex="-1" aria-labelledby="markAvailableModalLabel" aria-hidden="true">
		<div class="modal-dialog modal-dialog-centered">
			<div class="modal-content">
			<div class="modal-header">
				<h1 class="modal-title fs-5" id="markAvailableModalLabel">Confirmation</h1>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				Are you sure you would like to mark this event as available? This change will be reflected immediately. 
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
				<button type="button" class="btn btn-primary" onclick="changeAvailability('markAvailable');return false;">Proceed</button>
			</div>
			</div>
		</div>
    </div>
    
	<div class="row">	
		<!-- First column -->
      	<div class="col">
			
			<div id="event-carousel" class="carousel slide" data-interval="false" data-value="{{img_ids|length}}" style="text-align: center;">
				<div class="carousel-inner" id="carouselInner">
				  	{% for img_id in img_ids %}
						<div class="carousel-item" id="{{img_id}}">
							<img src="/freefood/image-by-id/{{img_id}}" class="d-block img-col-fit" style="height:60vh; width:100%; overflow:hidden;">
						</div>
					{% endfor %}
					<!-- No images are present, we need a default -->
					{% if img_ids|length == 0 %}
						<div class="carousel-item">
							<img src="/static/freefood/default_image.png" class="d-block img-col-fit" style="height:60vh; width:100%; overflow:hidden;">
						</div>
					{% endif %}

				</div>
				
				{% if img_ids|length > 1 %}
					<button class="carousel-control-prev" type="button" data-bs-target="#event-carousel" data-bs-slide="prev">
						<span class="carousel-control-prev-icon" aria-hidden="true"></span>
						<span class="visually-hidden">Previous</span>
					</button>
					<button class="carousel-control-next" type="button" data-bs-target="#event-carousel" data-bs-slide="next">
						<span class="carousel-control-next-icon" aria-hidden="true"></span>
						<span class="visually-hidden">Next</span>
					</button>
				{% endif %}

			</div>

			<br>

			
			<div class="container">
				<div class="row">
					<div class="col-9">
						<label for="user-submit-rating-stars">Your Rating</label>
						<div id="user-submit-rating-stars" data-rating="{{preexisting_rating}}">
							{% for star_num in "12345"|make_list %}
								<span id="star-{{star_num}}" class="clickable-star" data-value="{{star_num}}"><i class="fa fa-star fa-2x"></i></span>
							{% endfor %}
						</div>
					</div>
					<div class="col-3">
						<!-- Visibility for these elements are maintained in the javascript file.  -->
						<div class="hidden" id="submit-rating-indicator"><i class="fa-solid fa-square-check"></i> Submitted</div>
						<span id="clear-rating" class="clickable-star">Clear</span>
					</div>
				</div>
			</div>
			
			<br>


			<!-- Image Carousel upload form -->
			<div class="container">
				<label for="add-image-form">Upload Image</label>
				<form class="mx-auto needs-validation" method="POST" action="{% url 'event_page' id %}" id="add-image-form"  enctype="multipart/form-data">
					{% csrf_token %}

					<div class="input-group">
						{% render_field imageForm.image class="form-control" aria-describedby="inputGroupFileAddon04"%}
						<button class="btn btn-primary" type="submit" id="inputGroupFileAddon04">Upload</button>
					</div>
					{% include "freefood/subtemplates/new_event_help_errors.html" with field=imageForm.image %}

				</form>
			</div>
			
		<h1>&nbsp</h1>
		</div>

		<!--  Second column -->
		<div class="col">
			<h4>					 
				<span id="event-rating" data-value="{{ rating }}" data-bs-toggle="popover" data-bs-trigger="hover focus" data-bs-content="Rating: {{ rating_precise }}, Number: {{ rating_num }}">
				{% for star_num in "12345"|make_list %}
					<span id="star-rating-{{ star_num }}"><i class="fa fa-star"></i></span>
				{% endfor %}
				</span>
			</h4>

			<page-title>{{title}}</page-title>

			<h5><b>Food:</b> {{food}}</h5>

			<h5><b>Location:</b> <a style="color: rgb(119, 112, 210) !important;" href="https://www.google.com/maps/place/{{latlng}}" target="_blank"> {{location}} </a></h5>

			<h5><b>Date:</b> {{date}} &nbsp | &nbsp <b>Time:</b> {{time}}</h5>
			
			<h5>
				{% if notes %}
					<b>Notes:</b> 
					{{notes}}
				{% endif %}
			</h5>

			<h5>
				{% if dietary_options %}
					<b>Dietary Options:</b>
					{% for option in dietary_options %}
						<button disabled class="btn btn-outline-secondary">{{ option }}</button>
					{% endfor %}
				{% endif %}
			</h5>

			<!-- change to actual website -->
			<button class="btn btn-primary btn-lg" style="width:150px; font-size:20px;  margin-right:10px;">
				<a href="mailto:?subject=Check out this free food&amp;body=There's free food on campus! More details here http://www.website.com."style="color:white !important; text-decoration:none;">
					Share
					<i class="fa fa-envelope"></i>
				</a>
			</button>

			<hr style="height:4px; background-color:rgb(41, 26, 134);">


			<h3>Comments</h3>

			<div>

				<div class="input-group mb-3">
					<div class="form-floating">
						<textarea class="form-control" id="id_comment_input_text" name="new-comment" placeholder="Leave a comment here" required></textarea>
						<label for="new-comment">Comment</label>
					</div>
					<button class="btn btn-outline-secondary" id="addon-btn" onclick="addComment();return false;">Submit</button>
				</div>
				
				<div id="my-comments" style="border-radius:10px; background-color:rgba(255, 255, 255, 0.491); width:100%; max-height:40vh; overflow-y:scroll; text-align:left;"> </div>
				&nbsp
				<script>
					window.onload = loadComments;
					window.setInterval(loadComments, 5000);
				</script>
				<!-- <div class="invalid-feedback"></div> -->
			</div>
		</div>
	</div>
</div>




{% endblock %}

freefood/templates/freefood/heatmap.html
{% extends "freefood/base.html" %}

{% block scripts %}<script src="/static/freefood/heatmap.js"></script>{% endblock %}

{% block title %}HeatMap{% endblock %}

{% block header %}
	{% include "freefood/subtemplates/header.html" with page="heatmap" %}
{% endblock %}

{% block body %} 

<page-title style="margin:10px;">Heat Map</page-title>
<p style="margin-left:10px;">This heatmap shows where all past food events were held. This displays the historically most popular areas that would give away free food.</p>


<div id="heatmap"></div>


<script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB4--DpVDid7yY_Uqt6Pm1NL_NSN2eSty4&callback=initMap&v=weekly&libraries=visualization"
    defer>
</script>

{% endblock %}

freefood/templates/freefood/map.html
{% extends "freefood/base.html" %}

{% load widget_tweaks %}

{% block scripts %}
<script src="https://kit.fontawesome.com/980e4cc40c.js" crossorigin="anonymous"></script>
<script src="/static/freefood/maps.js"></script>
{% endblock %}

{% block title %}Map{% endblock %}

{% block header %}
	{% include "freefood/subtemplates/header.html" with page="map" %}
{% endblock %}

{% block body %} 
<div class="container-fluid">
    {{ message }}
    <!-- Display errors from AJAX requests?? -->
    <div id="error"></div>
  
    <div class="row" style="padding: 10px;">
        <div class="container">

            <!-- Sort button dropdown -->
            <span class="dropdown" style="z-index:10000;">
                <button id="sort-button" class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Sort: {{ sortMethod }}
                </button>
                <ul class="dropdown-menu">
                  <li><button class="dropdown-item" type="button" onclick="recentSort();return false;">Recent</button></li>
                  <li><button class="dropdown-item" type="button" onclick="ratingSort();return false;">Rating</button></li>
                  <li><button class="dropdown-item" type="button" onclick="popularitySort();return false;">Popularity</button></li>
                  <li><button class="dropdown-item" type="button" onclick="commentsSort();return false;">Comments</button></li>
                </ul>
            </span>

            <!-- Date filter -->
            {% if DateRangeForm %}
            <span class="dropdown" style="z-index:10000;"> 
                <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" data-bs-auto-close="outside" id="date-filter-dropdown-button">
                    {{ DateRangeLabel }}
                </button>
                <form class="dropdown-menu p-4" method="POST" action="{% url 'update-date' %}" id="date-filter-form">
                    {% csrf_token %}

                    <label class="form-label" for="date-ranges-label">Select a Range</label> 
                    <div class="form-floating" id="date-ranges-label">
                        {% render_field DateRangeForm.startDate class="form-control" type="date" %}
                        <label for="id_startDate">Start</label>
                        {% include "freefood/subtemplates/new_event_help_errors.html" with field=DateRangeForm.startDate %}
                    </div>
                    <div class="form-floating">
                        {% render_field DateRangeForm.endDate class="form-control" type="date" %}
                        <label for="id_endDate">End</label>
                        {% include "freefood/subtemplates/new_event_help_errors.html" with field=DateRangeForm.endDate %}
                    </div>

                    <li><hr class="dropdown-divider"></li>
                    <button type="submit" class="btn btn-primary">Save</button>
                </form>
            </span>
            {% endif %}


            {% if RestrictionsForm %}
            <!-- Dietary restrictions -->
            <span class="dropdown" style="z-index:10000;">
                <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" data-bs-auto-close="outside" id="dietary-dropdown-button">
                    {{ RestrictionsLabel }}
                </button>
                <form class="dropdown-menu p-4" method="POST" action="{% url 'update-dietary' %}" id="dietary-restrictions-form">
                    {% csrf_token %}
                    <div class="form-check">
                        {% render_field RestrictionsForm.veg type="checkbox" class="form-check-input" %}
                        <label class="form-check-label" for="id_veg">
                        Vegetarian
                        </label>
                    </div>

                    <div class="form-check">
                        {% render_field RestrictionsForm.vn type="checkbox" class="form-check-input" %}
                        <label class="form-check-label" for="id_vn">
                        Vegan
                        </label>
                    </div>

                    <div class="form-check">
                        {% render_field RestrictionsForm.df type="checkbox" class="form-check-input" %}
                        <label class="form-check-label" for="id_df">
                        Dairy-Free
                        </label>
                    </div>

                    <div class="form-check">
                        {% render_field RestrictionsForm.gf type="checkbox" class="form-check-input" %}
                        <label class="form-check-label" for="id_gf">
                        Gluten-Free
                        </label>
                    </div>

                    <li><hr class="dropdown-divider"></li>
                    <button type="submit" class="btn btn-primary">Save</button>
                </form>
            </span>
            {% endif %}

            {% if HappeningNow %}
            <button id="active-filter-btn" class="btn btn-primary" type="checkbox"
                onclick="toggleShowNow();return false;"> Show All </button>
            {% else %}
            <button id="active-filter-btn" class="btn btn-primary" type="checkbox"
                onclick="toggleShowNow();return false;">Hide Finished </button>
            {% endif %}
            
        </div>

    </div>


    <!-- Content (holds the event information cards and the map)-->
    <row class="row">
        <div class="col-3 map-column">
            <br>
            <!-- Placeholder for where AJAX html goes, plz leave untouched -->
            <div id="event-cards">
            </div>

        </div>
        
        <!-- Second column of the screen -->
        <div class="col-9">
            <div id="map"></div>
        </div>
    </row>

</div>


<script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB4--DpVDid7yY_Uqt6Pm1NL_NSN2eSty4&callback=initPage&v=beta&libraries=marker"
    defer>
</script>




{% endblock %}

freefood/templates/freefood/new_event.html
{% extends "freefood/base.html" %}

{% load widget_tweaks %}

{% block title %}New Event{% endblock %}

{% block scripts %}<script src="/static/freefood/new_event_map.js"></script>{% endblock %}

{% block header %}
    {% include "freefood/subtemplates/header.html" with page="new_event" %}
{% endblock %}

{% block body %}     
    <form action="{% url 'new_event' %}" method="POST" enctype="multipart/form-data" class="row g-3 container-sm mx-auto needs-validation" novalidate>
        <page-title>Create New Event</page-title>
        {% include "freefood/subtemplates/event_form.html" with form_function="Create Event" %}
    </form>
    
    <h1>&nbsp</h1>    

    <script>
        // by default load the current day in here
        document.getElementById('id_date').valueAsDate = new Date();
            
    </script>
{% endblock %}

freefood/templates/freefood/oauth_check.html
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Oauth Check</title>

        <!-- Bootstrap5 -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

        <link rel="stylesheet" href="/static/freefood/default.css">

        <!-- Google Font -->
        <link href="https://fonts.googleapis.com/css2?family=Poppins" rel="stylesheet">

        <!-- favicon -->
        <link rel="icon" type="image/x-icon" href="/static/freefood/ui/favicon.ico" >

        <!-- JQuerry -->
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"
            integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
            crossorigin="anonymous">
        </script>
    </head>

    <header>
        <div id="id_header_div" class="header">
            <a class="header-title" id="id_site_name" >
                <img src="/static/freefood/ui/logo.png" style="width:40px;">
                Free Food @ CMU
            </a>
        </div>
    </header>

    <body>  
        <div id="id_header_div">
            
            <div style="margin:50px">
                <h4>{{ message }}</h4>
                <h4>Please sign in with a new account.</h4>
                <button class="btn btn-primary btn-lg" style="width:300px;">
                    <a href="{% url 'logout' %}" style="color:white !important; text-decoration:none;">Try Again!</a>
                </button>
            </div>
        </div> 
    </body>
</html>